google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClient.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/EnhancedBigQueryReadStubSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ReadRowsResumptionStrategy.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/package-info.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/stub/EnhancedBigQueryReadStubSettingsTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/stub/ResourceHeaderTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ReadRowsRetryTest.java

This pull request creates an enhanced shim layer in the BigQuery Storage API v1beta2 client in order to apply a streaming resumption strategy for the ReadRows method.
* First commit creates the enhanced shim layer
* Second commit adds the custom streaming resumption strategy
The changes are similar to the PR for v1beta1: https://github.com/googleapis/google-cloud-java/pull/4022. The difference is that a lot of the timeout and retry settings are now automatically applied on the base (auto-generated) client.
Some tips on how to review the PR and which files to compare:
* `EnhancedBigQueryReadStub.java` is based from `BigQueryReadStub.java`
* `EnhancedBigQueryReadStubSettings.java` is based from `BigQueryReadStubSettings.java`
* `BigQueryReadSettings.java` is based from …

feat: add an enhanced layer for BigQuery Storage v1beta2 client

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/BigQueryResource.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryStorageLongRunningTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryStorageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/SimpleRowReader.java

The tests are the same as in v1beta1, with some minor differences due to protocol buffer changes.
CC: @kmjung

feat: add integration tests for v1beta2 BigQuery Storage API

---

google-cloud-bigquerystorage/pom.xml
pom.xml

deps: bump dependency versions

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClient.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStubSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ReadRowsResumptionStrategy.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/package-info.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStubSettingsTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/stub/ResourceHeaderTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ReadRowsRetryTest.java

This pull request creates an enhanced shim layer in the BigQuery Storage API v1 client in order to apply a streaming resumption strategy for the ReadRows method.
* First commit copies the enhanced shim layer from v1beta2, since v1 and v1beta2 APIs are identical.
* The files in this commit are just a copy, with no changes, from v1beta2. The commit exists just to make it easier to review the actual changes that are in the second commit.
* Second commit just updates the version of the files from the v1 enhanced shim layer
@kmjung , please review the changes.

feat: add an enhanced layer for BigQuery Storage v1 client

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/BigQueryResource.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryStorageLongRunningTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryStorageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/SimpleRowReader.java

This change adds integration tests for the BigQuery Storage v1 API.
The tests are identical to the ones from v1beta2.
* First commit copies the v1beta2 integration tests as-is, without any modifications.
* This commit makes it easier to review the second commit
* Second commit updates the version of the integration tests.

feat: add v1 integration tests

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverterTest.java
google-cloud-bigquerystorage/src/test/proto/test.proto
pom.xml

Add a client library addition to convert users schemas from the output of Descriptor.toProto to API acceptable ProtoSchema. This is needed for all users using the Write API.
The DescriptorProto needs to be self contained (contains all referenced type definition) so that server can reconstruct the schema from scratch.

feat: proto converter library

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/it/ITBigQueryWriteManualClientTest.java

Fixes #140 ☕️
After the fix, close() should fully work. So I updated the unit test to use close().
Also fixed a issue in reconnection.

fix: waitForTermination in the manual client #140

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompact.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/FakeBigQueryWrite.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/FakeBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/MockBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompactTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCacheTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/it/ITBigQueryWriteManualClientTest.java

Fixes #164 ☕️
Implementation of DirectWriter which allows users to write to BigQuery in one call. Deduplication is not supported but it should be enough for most common write scenarios.

feat: Direct writer

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/Waiter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java

- Make messages wait in flow control to be delivered in order
- Avoid recreating the BigQueryWriteClient stub during reconnection, which is not necessary.
- Allow user to pass in BigQueryWriteClient stub so that it can be shared with other API calls.

fix: several StreamWriter issues

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCacheTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/it/ITBigQueryWriteManualClientTest.java

1. There are some warnings in the test runs saying that open connections are not closed. Make sure everything is shutdown after test.
2. There is some unexpected exceptions thrown which is not caught. Now catch a more general exception and also fix some issues that incorrectly calling remove on List (which is not supported).
3. Make sure the executor in the tests are finished running, so it will not run into a race with test shutdown.

fix: flaky writeapi manual client tests

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCacheTest.java

- Fix some unwanted exceptions in the test run by make sure writers are cleaned up.
- Fix another executor race issue.
- The reconnection test failure is wired, it seems the test was shut down while running. I split the tests into 3 and reduce its run length. It could be due to testing taking too long to run (each wait is 7 seconds and there were 4 waits).

fix: more writeapi manual client test issues

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java

There is a test flakiness that sometimes, we get unexpected StatusUnknown error set from stream closed. It could be a error race that the second error overrides the first error.

fix: Avoid setting error on response future twice

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java

Make custom executor no longer pass down to BigQueryWriteClient. The user have a choice of setting a custom BigQueryWriteClient nowadays. The custom executor will only be used in the scope of StreamWriter. This will reduce one test run time by 1 minute.

fix: try to make test run a bit faster, and update some logs.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/FakeBigQueryWrite.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/FakeBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/it/ITBigQueryWriteManualClientTest.java

Add a flush method to StreamWriter. The implementation is void, so just added boilerplate unit test and e2e test.

feat: Add flush API to StreamWriter

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java

There isn't enough log to understand what's going on, make the test info more specific about this particular test.

fix:add more diagnostic info for test awaitTermination

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ReadRowsAttemptCallable.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ReadRowsRetryingCallable.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClientTest.java

fix: add retry logic for readrows

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ReadRowsAttemptCallable.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ReadRowsRetryingCallable.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java

fix: add retry logic for readrows v1beta2

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ReadRowsAttemptCallable.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ReadRowsRetryingCallable.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClientTest.java

fix: add retry logic for readrows v1beta1

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibility.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibilityTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCacheTest.java

Renamed SchemaCompact.java to SchemaCompatibility.java and changed all instances of SchemaCompact to be SchemaCompatibility in other files.

fix: Renamed SchemaCompact.java to SchemaCompatibility.java

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibility.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibilityTest.java

Fixed a bug and made BQ Numeric compatible with double and float protobuf types.

fix: BQ Numeric is compatible with double and float protobuf types

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Change BQ Date to map to Proto Int32.

fix: BQTableSchemaToProtoDescriptor change type mapping

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java

Add 'Received Rst Stream' to automatic retry strings

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Since the backend is case-insensitive, letting all fieldnames be lowercased in the generated protobuf descriptor can save some space/time while using the generated descriptor to create a protobuf message from JSON.

fix: BQTableSchemaToProtobufDescriptor will now only generate lower-cased fieldnames in the protobuf descriptor

---

proto-google-cloud-bigquerystorage-v1beta1/pom.xml

These dependencies were not added to the `pom.xml` by the generator when resource name classes were added. I'm not sure why that is, but it will fix the CI errors in #435. I tested this locally and noted it in the config change.

fix: add missing resource name deps to v1beta1

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
pom.xml

Added JsonToProtoMessage.java which can convert json data to protocol buffer data given the protocol buffer descriptor.

feat: Adding JsonToProtoMessage.java

---

samples/snippets/src/main/java/com/example/bigquerystorage/StorageSample.java

refactor(samples): update region tag

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverterTest.java
synth.metadata

fix: enum value conflict in generated ProtoSchema descriptor.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibility.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibilityTest.java

fix:update schema compat check with backend type changes

---

renovate.json
synth.py

it's not java7 compat
this allows us to permanently close #545

chore: exclude org.apache.commons:commons-lang3 from renovate-bot updates

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
pom.xml
renovate.json

fix: remove apache commons lang

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriterTest.java

fix: exception tests

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/it/ITBigQueryWriteManualClientTest.java

fix: test failure due to message start appending entity

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/JsonWriterCache.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonWriterCacheTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCacheTest.java

fix: Remove stream ttl in client library, since there is no very clear TTL defined.

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java

fix: A test race in JsonStreamWriterTest 

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

fix: Add special type tests for Json writer and fix some type mapping issues

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

fix: Temporally disable test/code where breaking change is used to help pushing out the breaking change in unreleased Beta

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
proto-google-cloud-bigquerystorage-v1beta2/clirr-ignored-differences.xml

Original PR opened by @yirutang : https://github.com/googleapis/java-bigquerystorage/pull/755
IgnoreUnknownFields is no longer supported on API level. So make JsonStreamWriter consistent with it.

feat: remove IgnoreUnknownFields support on JsonStreamWriter

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

fix: An extra test that is still calling old JsonStreamWriter append

---

synth.py

prevent PRs like https://github.com/googleapis/java-bigquerystorage/pull/777 from being generated

chore: fix nit

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

fix: StreamWriter hang when we reach the inflight limit control and is doing a retry

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

fix: add dataflow trace id support

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

…l to release the requests in the queue, causing shutdown to wait forever

fix:shutdown stuck when there is error on the flush path

---

pom.xml

looks like staging is still going to oss.sonatype.com. this should hopefully fix that.

ci: re-configure plugin to test out new sonatype google endpoint

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/Waiter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

Since there is major refactoring needed in order for this to work smoothly, temporarily remove this feature and let client retry connection. Also remove a flaky test FlushAllFailed, that feature is going to be removed in another PR.

fix: remove reconnection feature from client library

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

fix: Remove flushAll method

---

.github/sync-repo-settings.yaml

This gives api-bigquerystorage team members `write` access to the repo.

chore: update api-bigquerystorage team access from admin to push

---

google-cloud-bigquerystorage/pom.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamConnection.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/FakeBigQueryWrite.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/FakeBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2Test.java

feat: Create Stream writer v2 - starting with core logics

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2Test.java

feat: Support building a BigQueryWriteClient within the StreamWriterV2

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2Test.java

feat: StreamWriterV2 sets exception for response with error

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2Test.java

…the connection and remove stream name and schema in the following ones.

feat: StreamWriterV2 will handle schema/streamName attachment

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

fix:test failure testAppendWhileShutdownSuccess

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java

fix: testAppendWhileShutdownSuccess race

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

1. Add schema update back to json writer by recreate the stream.
2. Remove the batching support on json writer so that potentially it can be moved to use StreamWriterV2. This is to avoid users become dependent on the feature. Currently the move is not possible because StreamWriterV2 is lacking the schema update callback feature. It can probably be done inside json writer as well, but will do this later.
3. Also remove RetrySetting ExecutorSetting to be more consistent with what we actual support right now.

fix: add schema update back to json writer

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

fix: Revive schema update e2e test and adjust some test names

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2Test.java
samples/snippets/src/main/java/com/example/bigquerystorage/ParallelWriteCommittedStream.java

feat!: remove deprecated append method in StreamWriterV2

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java

fix: add a deprecation message on StreamWriter

---

samples/snippets/src/main/java/com/example/bigquerystorage/WritePendingStream.java

If the returned BatchCommitWriteStreamsResponse does not have a commit time, it means an error occurred.

docs(samples): Check for error from BatchCommitWriteStreams

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigDecimalByteStringEncoder.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigDecimalByteStringEncoderTest.java

feat: BigDecimal and ByteString encoding

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

fix: Cleanup JsonWriter bytes conversion code and add some test coverage

---

google-cloud-bigquerystorage/pom.xml
pom.xml

Build failure observed in https://github.com/googleapis/java-bigquerystorage/pull/1000/checks?check_run_id=2325305545 when [updating libraries-bom](https://github.com/googleapis/java-bigquerystorage/pull/999):
```
Error:  Plugin com.google.protobuf.tools:maven-protoc-plugin:0.4.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.google.protobuf.tools:maven-protoc-plugin:jar:0.4.2: Could not transfer artifact com.google.protobuf.tools:maven-protoc-plugin:pom:0.4.2 from/to protoc-plugin (https://dl.bintray.com/sergei-ivanov/maven/): Authorization failed for https://dl.bintray.com/sergei-ivanov/maven/com/google/protobuf/tools/maven-protoc-plugin/0.4.2/maven-protoc-plugin-0.4.2.pom 403 Forbidden -> [Help 1]
```

chore: update protoc plugin to address build failure observed

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryBigDecimalByteStringEncoderTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryTimeEncoderTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

fix: migrate json writer to use StreamWriterV2

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/util/Errors.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/util/ErrorsTest.java

- [ x ] Ensure the tests and linter pass
- [ x ] Code coverage does not decrease (if any source code was changed)
This change makes error matching against stream rst more robust.  Customers have started to see other variants with RST stream.  The capitalization of "Rst Stream" isn't clear, other repose have it lower cased: (e.g. https://github.com/googleapis/java-bigtable-hbase/pull/3000/files)

fix: More robust STREAM_RST logic

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/util/Errors.java

fix: Make EOS Matching more robust
Clients are seeing a different variant now: Received unexpected EOS on empty DATA frame from server

fix: Make EOS Matching more robust

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java

Make "offset" stand out a bit more in this append example because it's an important param to ensure ordering and deduplication.

samples: indicate offset in append operation explicitly in a comment

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

Fixes a broken URL in a sample comment.
Also cleans up the docstrings for `streamOrTableName` in `JsonStreamWriter.Builder`.
IIUC, `createDefaultStream` can only be set to True on `StreamWriter` not `JsonStreamWriter`, the language below could mislead devs into thinking otherwise because it's not clear which `builder` it refers to.  
https://github.com/googleapis/java-bigquerystorage/blob/d6c3146d21282d1e0724583f68a31184d2d7167b/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java#L185-L188
Also it looks like `_default` is not added by client code but by the library.
https://github.com/googleapis/java-bigquerystorage/blob/d6c3146d21282d1e0724583f68a31184d2d7167b/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storag …

docs: user-provided streamOrTableName for default write streams

---

samples/snippets/src/test/java/com/example/bigquerystorage/WriteToDefaultStreamIT.java

docs(sample): add IT for WriteToDefaultStream

---

google-cloud-bigquerystorage-bom/pom.xml

All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.

chore: remove distributionManagement section

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java

feat: Expand bytes field type handling

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java

See details in #1246 .
This is a suggestion from Google's support (Case#28707078) which I am documenting here in case others stumble upon this issue.
It is odd that passing the `client` triggers the error therefore this PR only aims to fix the sample rather than working out the production code (which is still in PRE-GA so issues are expected). Feel free to close this PR if the production code is fixed instead in the meantime (which is preferable).
Let me know if I need add more details on the issue. I omitted as the linked ticket includes the details.
Fixes #1246 ☕️
--- 
- ~[ ] Code coverage does not decrease (if any source code was changed)~

docs(sample): Fix `PERMISSION_DENIED` in `WriteCommittedStream`

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/util/Errors.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClient.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClient.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClient.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadSettings.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/EnhancedBigQueryReadStub.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/util/ErrorsTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClientTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java

Bq Storage Read service will start returning a retryable RESOURCE_EXHAUSTED error in the next few weeks when a read session's parallelism is considered to be excessive, so this PR expands retry handling logic for ReadRows with 2 changes:
1. If a ReadRows request fails with a RESOURCE_EXHAUSTED error and the error has an associated RetryInfo, it is now considered to be retryable and retry delay is set according to the RetryInfo.
1. If the client decides to retry, it now notifies the user with the provided RetryAttemptListener object. This will be useful as a negative feedback mechanism for future SplitReadStream requests which in return will reduce the likelihood of receiving the new retryable RESOURCE_EXHAUSTED error.

feat: retry certain RESOURCE_EXHAUSTED errors observed during ReadRows and report retry attempts

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java

feat: add trace id support to JsonWriter and add default trace id to help identify json writer users.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Fixes #1396
1. Long values are converted into Integer for DATE fields.
2. Date literals are converted into epoch days (Integer) for DATE fields.
3. Number values are converted into Double for DOUBLE fields.

feat: DATE and DOUBLE support more input formats

---

samples/install-without-bom/pom.xml
samples/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml

Reverts googleapis/java-bigquerystorage#1428
Due to below error caused:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default-cli) on project bigquerystorage-snippets: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2 or one of its dependencies could not be resolved: Could not find artifact com.google.cloud.samples:checkstyle-configuration:jar:1.0.24 in central (https://repo.maven.apache.org/maven2) -> [Help 1```

revert: "chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.0.24"

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigDecimalByteStringEncoder.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

fix: finish BIGNUMERIC support

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

Fixes b/197450141
https://sfstory.googleplex.com/29256923

fix: allow all fields to be null values

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

feat: support `append()` without offset in `StreamWriter`

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

feat: Add ignoreUnknownField support in JsonWriter

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

client-side changes corresponding to cl/408735437

fix: update storageError support due to server side enhancement

---

README.md
samples/snippets/src/main/java/com/example/bigquerystorage/WriteBufferedStream.java
samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

docs(samples): add finalize call to our samples

---

google-cloud-bigquerystorage/src/test/resources/META-INF/native-image/reflect-config.json

This PR adds reflection configuration for native-image testing. Currently running `mvn test -Pnative` caused `ITBigQueryWriteManualClientTest` to fail at the native image build step. 
```
Caused by: java.lang.IllegalArgumentException: key v, field private java.lang.Object com.google.api.services.bigquery.model.TableCell.v
com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900)
com.google.api.client.json.JsonParser.parse(JsonParser.java:451)
com.google.api.client.json.JsonParser.parseValue(JsonParser.java:787)
[...]
Caused by: java.lang.IllegalArgumentException: unable to create new instance of class java.lang.Object because it has no accessible default constructor
com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:162) …
```

fix(java): add reflection configuration for native-image testing

---

google-cloud-bigquerystorage/pom.xml

Fixes b/216195517
Exclude:
```
io.grpc:grpc-xds:jar:1.42.1:runtime
io.grpc:grpc-services:jar:1.42.1:runtime
com.google.re2j:re2j:jar:1.5:runtime
org.bouncycastle:bcprov-jdk15on:jar:1.67:runtime
io.opencensus:opencensus-proto:0.2.0:runtime
```

deps: exclude un-used runtime dependencies brought in by gax-grpc

---

pom.xml

This addresses gRPC CVE by upgarding to v1.44.0. Note that gRPC dropped Java 8 support in this version.

deps: upgrade google-cloud-shared-dependencies to v2.7.0

---

tutorials/README.md

docs(tutorials): add a README.md

---

tutorials/JsonWriterDefaultStream/JsonWriterDefaultStream.java
tutorials/JsonWriterDefaultStream/README.md
tutorials/JsonWriterDefaultStream/pom.xml

- Add a readme file
- Fix the POM file for the current directory structure
- Change one schema field in the sample

docs(tutorials): Add README, other small fixes to JsonWriterDefaultStream tutorial

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

feat: add a indicator of how much time a request is waiting for inflight limit

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

fix: add more idiomatic way to insert ARRAY<BYTES> data

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

feat: add JsonToProtoMessage support for TIMESTAMP

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java

Also clean up the code to reconnect after 10MB.

fix: a possible race condition that we used table schema out of the lock.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Closes #1586, this allows users to send strings of numerics to the api and have them case properly into the correct numeric type.

feat: string to correct type (INT32, INT64, FLOAT, BOOLEAN)

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Using: https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java#L79 we can construct something similar here, to allow for better ISO8601 compliance.
Fixes #1579 
Fixes #1580

fix: better ISO8601 compliance

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

fix: even better ISO compilance

---

README.md
samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

docs(sample): update WriteToDefaultStream sample to match best practices

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

Add a timeout of one minute waiting for done callback to be called. Same timeout as client close.
The donecallback mainly gives back the server side error status, so it is not critical. In Dataflow connector, we saw hang because the DoneCallback is lost and we wait forever on it.
Stack trace in b/230501926

fix: A stuck when the client fail to get DoneCallback

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Add a throwException behavior when the StreamWriter inflight queue is full.
Fixes #1539 ☕️

fix: Add a throwException behavior when the StreamWriter inflight queue is full

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Also change the exception rejection into before the request was added to the queue instead of after.

fix: add extra JsonWriterTest to show that the LimitBehavior addition is not breaking

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Should allow users to pass ints and longs as numerics.
Fixes #1516

fix: ints/longs are numerics

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Allows floating point numbers to be numerics and big numerics.
Fixes #1516

fix: doubles and floats as numerics

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

feat: Return explicit StreamWriterClosedException

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

In a retryable error case, if we close the writer, the only thing user can do is to recreate streamwriter and do the same thing. So remove RETRY_THRESHOLD so that user need to worry about one less issue.

feat: Add another StreamWriterClosedException and remove RETRY_THRESHOLD

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

Customer hitting a general grpc channel cancelled error due to server side cancel the channel:
throwable com.google.cloud.bigquery.storage.v1.Exceptions$StreamWriterClosedException: FAILED_PRECONDITION: Connection is closed due to com.google.api.gax.rpc.CancelledException: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
Since we have user_closed flag to guard writer close, it is fine to retry on Cancelled error, so user side saw less error.

feat: Add CANCELLED to StreamWriter retryable error code

---

README.md
google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

Remove a dummy WriterClosedException. Because we now have StreamWriterClosedException, remove the WriterClosedException to avoid confusion.
The WriterClosedException is used as a place holder when we cleanup Inflight request. In call cases, we should have gotten a not null connectionFinalStatus in WaitForDoneCallback:
https://github.com/googleapis/java-bigquerystorage/blob/main/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java#L533
So no user should be able to get this exception.

feat!: remove a dummy WriterClosedException

---

README.md
google-cloud-bigquerystorage/pom.xml

Fixing the test-scope dependency to runtime. The flatten maven plugin does not interpret test scope dependency correctly.
The test scope was added recently: https://github.com/googleapis/java-bigquerystorage/pull/1720/files#diff-273690ed1fb8c3821089309482b75cb6b6de18d07238cb82c74cb1855e215904 . This would cause problem like https://github.com/googleapis/java-pubsub/issues/1239

deps: fixing the test scope dependency to runtime

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Also introduced a unique writer Id so that users can use it to identify different writers.
Also moved StreamWriterClosedException out of StorageException, since it is a client side exception.

feat: introduce InflightLimitExceededException

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

Final status isn't set after retriable error, but if we're not connected, there's no point in waiting for a done callback.
Unit tests aren't set up for this, but verified by temporarily adding 10m wait to IT, which works after fix.

fix: Close based on whether connection is active, not status variable

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

fix: Add missing field error to row error message

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Also reduce wait from 5->3 minutes

fix: Add unit test for closing disconnected streamwriter. 

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

Fixes #[1761](https://github.com/googleapis/java-bigquerystorage/issues/1761) ☕️

fix: allow repeated field to have a null or missing json array

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

fix(api): Numeric/BigNumeric type conversion issue

---

.github/.OwlBot.yaml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

feat: introducing connection worker to run a loop for fetching / sending requests in a queue. This change is for the ongoing multiplexing client effort.

Multiplexing client: split writer into connection worker and wrapper

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

feat: Add fully managed schema support on json writer

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java

In order for regional routing to work, right now, we need to recreate a BigQueryWriteClient with custom header on StreamWriter. The new JsonWriter builder interface we added requires a not null BigQueryClient in order to be able to call GetWriteStream, if the user always pass in BigQueryWriteClient, in the current code, we reuses that BigQueryWriteClient and then the customer header will not be added and routing will fail.
So no matter whether we have an existing BigQueryWriteClient or not on the json writer, we always ask StreamWriter to create a new BigQueryWriteClient in order for routing to work. We are working on the backend to make this special workaround no longer needed.

feat: always pass a null bigquery client lib to StreamWriter

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

End to end tests added to test the [newBuilder() method](https://github.com/googleapis/java-bigquerystorage/pull/1794) added to JsonStreamWriter which enables users to create JsonStreamWriter without explicitly providing a Table Schema.
This PR has the following tests:
- Test to check that the JsonStreamWriter generated with the new methods works as expected.
- Test to check that the JsonStreamWriter generated with the newBuilder method is working exactly same as the JsonStreamWriter generated with older NewBuilder method by explicitly providingTableSchema.

chore: add test to check newBuilder for JsonStreamWriter

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/FakeBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java

feat: client unknown fields drives writer refreshment

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java

This PR is about if JsonStreamWriter already calls GetWriteStream to figure out the table's schema (should be what most users will use in the future), also populate location info from the result so that later on, we don't need to look up the location info again. Also added location accessor on StreamWriter and JsonStreamWriter.

feat: populate location info if we already called GetWriteStream

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java

An arbitrary ExecutorProvider can be set to control the generation of gax threads.
Fixes #1769

feat: ExecutorProvider can now be replaced

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

We have e2e test coverage here:
https://github.com/googleapis/java-bigquerystorage/blob/main/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java#L220

fix: remove the client lib header setting since after router migration, it is no longer needed

---

.github/.OwlBot.yaml
.kokoro/build.sh
google-cloud-bigquerystorage/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-bigquerystorage/reflect-config.json
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

This configuration was added in https://github.com/googleapis/java-bigquerystorage/pull/1488 but was removed by owlbot in https://github.com/googleapis/java-bigquerystorage/pull/1543. The build script changes were excluded from https://github.com/googleapis/java-bigquerystorage/pull/1362 so this missing configuration was only caught through manual testing by running `mvn test -Pnative`. This PR restores both changes.

fix(java): restore native image configurations

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
samples/snippets/src/main/java/com/example/bigquerystorage/WritePendingStream.java
samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

fix: update JsonStreamWriterBuilder comment and update sample to use the latest schema retrieval support

---

google-cloud-bigquerystorage/pom.xml

This could be the cause of frequent kokoro check failures.

chore: remove duplicate protobuf-java dependency

---

README.md
google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPool.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Most of the internal error is about a connection state being not correct, they should be able to be fixed by reconnect.
Also we recently changed the retry to be limited retry of 5 minutes, so there is less concern to add more error code to retry, since some uncoverable error will eventually error out.
Other customer issues regarding retry on internal error: b/266880584 b/267187413

fix: at connection level, retry for internal errors

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java

1. Add unique worker id.
2. Remove per request and per response logging.

fix: improve ConnectionWorker fine logging

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPool.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/FakeBigQueryWrite.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/FakeBigQueryWriteImpl.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java

Currently if StreamWriter is closed, in multiplexing mode, there is nothing to guard against append to happen again.
We still need StreamWriter has a closed state and we also need to tie it to all the StreamWriter's inflight request queue. I think we need to move back some of the "contractural" StreamWriter test case instead of moving them all down to ConnectionWorker.

feat: Add userClose flag back to StreamWriter

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java

feat: Add isDone to JsonWriter to indicate a JsonWriter is no longer usable and needs to be recreated.

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/proto/test.proto

fix: support ByteString values on repeated fields

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java

fix: extra logging for investigation of the stuck case.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPool.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPoolTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerTest.java

Write API is going to use GFE dynamic routing instead of global router. Once that is migrated, header is needed for routing decisions.

feat: Add header back to the client

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerTest.java

feat: add routing header for multiplexed connection

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

The request with the specific timeout exception, along with any aborted requests, must simply be caught and retried on a new StreamWriter.
If using connection pooling, creation of the new StreamWriter will be handled automatically by the connection pool. Otherwise, we manually create and switch to using a new JsonStreamWriter before re-sending the request.

chore: demonstrate how to handle an inflight request timeout exception

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
samples/snippets/src/test/java/com/example/bigquerystorage/WriteToDefaultStreamIT.java

Provide customers with a sample implementation of specifying a GEOGRAPHY table column.

chore: demonstrate writing a GEOGRAPHY field as string
