google-cloud-bigquerystorage-bom/pom.xml
grpc-google-cloud-bigquerystorage-v1alpha2/pom.xml
pom.xml
proto-google-cloud-bigquerystorage-v1alpha2/pom.xml

dep: bump v1alpha2 version

---

pom.xml

they have been added to java-shared-config

chore: remove flatten and ban duplicate class 

---

synth.py

Depends on https://github.com/googleapis/gapic-generator/issues/3181

chore: add temp code replacement hack due to gapic code-gen template bug

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java

fix: add some logging to investigate a test flakiness.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java

There is a test failure that we kept sending retry requests exceeding max attempt number.
Could be due to some race on currentRetries count? I couldn't repro it on my local machine.
Added some logging and moved currentRetries count after we set the exception.

fix: adding more logging to retry test

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java

fix: geo type accepted change from bytes to string

---

renovate.json

to put #547 at rest... for good.

chore: exclude org.apache.commons:commons-lang3 using ignoreDeps

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

fix: a build break caused by breaking change.

---

.kokoro/build.sh
.kokoro/nightly/samples.cfg
.kokoro/presubmit/samples.cfg
synth.py

To enable samples integration testing. Unblock #756 
cc @MikeWasson

ci: wire in secret manager for samples ITs

---

google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java

fix: default stream integration test failures due to production expected change

---

pom.xml

deps: update protobuf

---

pom.xml
renovate.json

@stephaniewang526 This doesn't appear to be used any more.

remove jackson dependency

---

.github/sync-repo-settings.yaml

@yirutang 
TeamSync team created: https://github.com/orgs/googleapis/teams/api-bigquerystorage

chore: create new team to better manage repo access

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptor.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigDecimalByteStringEncoder.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BQTableSchemaToProtoDescriptorTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessageTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryBigDecimalByteStringEncoderTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
google-cloud-bigquerystorage/src/test/proto/jsonTest.proto

test: BigDecmialByteStringConverter E2E Test

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java

fix: call awaitTermination when close the stream writer

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java

fix: update comment to be consistent with code

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java

Stream means metadata streams, StreamWriter is really about a connection. Change the name in error message to make it easier to distinguish from stream errors.

chore: update some names in error message from Stream to Connection

---

README.md
pom.xml
tutorials/JsonWriterDefaultStream/pom.xml
tutorials/JsonWriterDefaultStream/src/main/java/com/example/JsonWriterDefaultStream.java
tutorials/JsonWriterDefaultStream/src/test/java/com/example/JsonWriterDefaultStreamIT.java
tutorials/JsonWriterDefaultStream/src/test/resources/TestData.json

Includes two small code fixes:
- Change a field name in the schema.
- Detect schema updates while streaming.

docs(tutorials): Add IT to JsonWriteDefaultStream tutorial

---

.repo-metadata.json

Fixes internal data quality issue.

chore(docs): updating .repo-metadata for library_type

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 2.12.2

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java

docs(samples): update WriteComittedStream sample code to match best practices

---

README.md
google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java

fix: Add documentation to Exceptions

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

feat: add a new specific exception about json data has unknown field

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

feat: add more retry error code to the sample

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

exception.
feat: return list of row errors from append

fix: return row-level error information via an AppendSerializtionError

---

pom.xml

Reverts googleapis/java-bigquerystorage#1814

chore(deps): revert dependency com.google.cloud:google-cloud-shared-dependencies to v3.0.4

---

google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/Exceptions.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java
google-cloud-bigquerystorage/src/test/proto/test.proto

consuming errors as StatusRuntimeException

fix: breaking change to continue supporting users who may be

---

.github/.OwlBot.yaml

chore: fix owlbot.yaml

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPool.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java

fix: remove applying header for multiplexing client and add a unit test for multiplexing with different location

---

.github/release-please.yml
.github/sync-repo-settings.yaml
README.md

feat: next release from main branch is 2.26.0

---

README.md
google-cloud-bigquerystorage/clirr-ignored-differences.xml
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPool.java
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPoolTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerTest.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java

fix: we should isolate the client used in StreamWriter and the client used in ConnectionWorker

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BQTableSchemaToProtoDescriptor.java

This is a copy from the internal change cl/500839786.

fix: update BQTableSchemaToProtoDescriptor to unblock a protobuf change.

---

google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerTest.java

fix: remove write_location header pending discussion

---

README.md
google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java

fix(bigdecimal): Convert BigDecimal to BigNumeric instead of Numeric

---

samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java

feat: add sample code about default missingValueInterpretation
